export default {
  'smart-contracts': 'Smart Contracts',
  'api-reference': 'API Reference',
  architecture: 'Architecture',
  '---v7': {
    type: 'separator',
    title: 'Smart Contracts V7',
  },
  welcome: 'Welcome',
  'v7-overview': 'V7 Technical Overview',
  purpose: 'Purpose',
  privacy: 'Privacy',
  security: 'Security',
  automation: 'Automation',
  'erc-standards': 'ERC Standards',
  'eas-attestations': 'EAS and Attestations',
  'trust-graph': 'Contract Trust Graph',
  'immutable-registries': 'Immutable Registries',
  'document-registration': 'Document Registration',
  'tokenizer-contracts': 'ERC Tokenizer Contracts',
  messaging: 'Messaging',
  'delegated-execution': 'Delegated Execution',
  'web2-integration': 'Web2 Integration',
  extensibility: 'Extensibility',
  patterns: 'Patterns & Best Practices',
  guides: 'Integration Guides',
};
