export default {
  overview: 'Layer 3 Overview',
  'tokenizer-comparison': 'Tokenizer Comparison',
  BaseTokenizer: 'BaseTokenizer (Abstract)',
  TrustGraphIntegration: 'TrustGraphIntegration (Mixin)',
  IDocumentTokenizer: 'IDocumentTokenizer',
  OwnershipTokenizer: 'OwnershipTokenizer (ERC-721)',
  MultiPartyTokenizer: 'MultiPartyTokenizer (ERC-1155)',
  MultiPartyTokenizerLite: 'MultiPartyTokenizerLite (ERC-6909)',
  SharesTokenizer: 'SharesTokenizer (ERC-20)',
  RoyaltyTokenizer: 'RoyaltyTokenizer (ERC-1155)',
  RentalTokenizer: 'RentalTokenizer (ERC-1155)',
  BadgeTokenizer: 'BadgeTokenizer (ERC-1155)',
  SoulboundTokenizer: 'SoulboundTokenizer (ERC-721)',
  VaultTokenizer: 'VaultTokenizer (ERC-721)',
  SecurityTokenTokenizer: 'SecurityTokenTokenizer (ERC-20)',
  SemiFungibleTokenizer: 'SemiFungibleTokenizer (ERC-1155)',
};
